---

- name: Wrap /etc/issue message in cowsay
  ansible.builtin.command:
    cmd: "/usr/games/cowsay"
    stdin: "{{ motd_issue_message }}"
  changed_when: false
  register: motd_issue_cowsay_message
  when: motd_cowsay is true

- name: Wrap /etc/motd message in cowsay
  ansible.builtin.command:
    cmd: "/usr/games/cowsay"
    stdin: "{{ motd_message }}"
  changed_when: false
  register: motd_cowsay_message
  when: motd_cowsay is true

- name: Configure motd
  ansible.builtin.template:
    src: etc/motd.j2
    dest: '{{ motd_file }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
  when: motd_enable_motd

- name: Configure issue
  ansible.builtin.template:
    src: etc/issue.j2
    dest: '{{ motd_issue_file }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
  when: motd_enable_issue

- name: Configure issue.net
  ansible.builtin.template:
    src: etc/issue.j2
    dest: '{{ motd_issue_net_file }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
  when: motd_enable_issue_net

- name: Configure update-motd.d on Debian/Ubuntu
  when: ansible_os_family in ['Debian', 'Ubuntu']
  block:
    - name: Copy update-motd.d files
      ansible.builtin.copy:
        src: '{{ item.src }}'
        dest: '/etc/update-motd.d/{{ item.name }}'
        owner: root
        group: root
        mode: 0755
        seuser: system_u
        serole: object_r
        setype: etc_t
      loop: '{{ motd_update_motd_files }}'

    - name: Write update-motd.d file contents
      ansible.builtin.copy:
        content: '{{ item.content }}'
        dest: '/etc/update-motd.d/{{ item.name }}'
        owner: root
        group: root
        mode: 0755
        seuser: system_u
        serole: object_r
        setype: etc_t
      loop: '{{ motd_update_motd_file_contents }}'

    - name: Write update-motd.d templates
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '/etc/update-motd.d/{{ item.name }}'
        owner: root
        group: root
        mode: 0755
        seuser: system_u
        serole: object_r
        setype: etc_t
      loop: '{{ motd_update_motd_templates }}'

    - name: Write update-motd.d template contents
      ansible.builtin.template:
        src: '{{ item.content }}'
        dest: '/etc/update-motd.d/{{ item.name }}'
        owner: root
        group: root
        mode: 0755
        seuser: system_u
        serole: object_r
        setype: etc_t
      loop: '{{ motd_update_motd_template_contents }}'
