---

- name: configure motd
  ansible.builtin.template:
    src: etc/motd.j2
    dest: '{{ motd_file }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t

- name: configure issue
  ansible.builtin.template:
    src: etc/issue.j2
    dest: '{{ motd_issue_file }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t

- name: configure issue.net
  ansible.builtin.template:
    src: etc/issue.j2
    dest: '{{ motd_issue_net_file }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
