---

- name: Install motd related packages
  ansible.builtin.package:
    name: '{{ motd_packages }}'
    state: present

- name: Install cowsay packages
  ansible.builtin.package:
    name: 'cowsay'
    state: present
